CURRENT_LAYER_RESULT = "_y"
LAST_LAYER_RESULT = "_x"
LAYER_WEIGHTS = "_w"
LAYER_BIASES = "_b"

NO_DEFINITION = "NO_DEFINITION"
UNDEFINED_DESCRIPTOR = "UNDEFINED"

FORWARD_PASS = "forward_pass"
BACKWARD_PASS = "backward_pass"
DEFAULT_PASSES = [FORWARD_PASS, BACKWARD_PASS]