# PROGRAM BUILDER AND PROGRAM
CURRENT_LAYER_RESULT = "_y"
LAST_LAYER_RESULT = "_x"
LAYER_WEIGHTS = "_w"
LAYER_BIASES = "_b"
LAYER_ACTIVATION_DERIVATIVE = "_a"

NO_DEFINITION = "NO_DEFINITION"
DEPENDENT_CODE_DESCRIPTOR = "DEPENDENT_CODE"

FORWARD_PASS = "forward_pass"
BACKWARD_PASS = "backward_pass"
DEFAULT_PASSES = [FORWARD_PASS, BACKWARD_PASS]

INPUTS = "inputs"
EXPECTED = "expected"

# PROGRAM BUILDER ONLY
COST_VALUES = "cost_values"
BACKWARD_VALUES = "backward_values"
COST_BACKWARD_PARTIAL = "cost_values_backward_values_partial"

UPDATE_WEIGHTS = "update_weights"
UPDATE_BIASES = "update_biases"